# Generated by Django 4.0.2 on 2022-02-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options_comment_email_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='blog.post'),
        ),
    ]
