# Generated by Django 4.0.2 on 2022-02-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_name_category_name_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='content',
        ),
    ]
