# Generated by Django 4.0.2 on 2022-02-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.CharField(max_length=30),
        ),
    ]
